---

- name: Install nginx
  apt: name=nginx update_cache=yes

- name: remove default conf
  file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: Copy main config
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/

- name: Copy blog config
  copy:
    src: "{{ role_path }}/files/rockyj.conf"
    dest: /etc/nginx/sites-enabled/

- name: remove default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: restart nginx
  systemd: name=nginx state=restarted
