---
- name: Setup the server
  hosts: app-server
  become: yes
  become_method: sudo
  vars:
    ssh_port: 22
    domain_name: rockyj.in

  pre_tasks:
    - name: remove root ssh
      file:
        path: /root/.ssh/authorized_keys
        state: absent

    - name: install fail2ban
      apt: name=fail2ban update_cache=yes

    - name: install ufw
      apt: name=ufw update_cache=yes

    - name: install curl
      apt: name=curl update_cache=yes

    - name: install htop
      apt: name=htop update_cache=yes

    - name: install wget
      apt: name=wget update_cache=yes

    - name: install git
      apt: name=git update_cache=yes

  roles:
    - unattended
    - deployer
    - docker
    - dcompose
    - nginx

  post_tasks:
    - file:
        path: /opt/db/data
        state: directory
        mode: 0755
        owner: rockyj


