---
- name: Setup the server
  hosts: app-server
  become: yes
  become_method: sudo
  vars:
    ssh_port: 22
    domain_name: rockyj.in

  pre_tasks:
    - name: install fail2ban
      apt: name=fail2ban update_cache=yes

    - name: install ufw
      apt: name=ufw update_cache=yes

    - name: install curl
      apt: name=curl update_cache=yes

    - name: install htop
      apt: name=htop update_cache=yes

    - name: install wget
      apt: name=wget update_cache=yes

    - name: install git
      apt: name=git update_cache=yes

    - name: add certbot repo
      apt_repository:
        repo: 'ppa:certbot/certbot'
        update_cache: yes

    - name: install nginx certbot
      apt: name=python-certbot-nginx update_cache=yes

  roles:
    - unattended
    - deployer
    - docker
    - dcompose
    - nginx

  post_tasks:
    - file:
        path: /opt/db/data
        state: directory
        mode: 0755
        owner: rockyj


