---

- name: Install docker deps
  apt: name=apt-transport-https,ca-certificates,software-properties-common update_cache=yes

- name: Add key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Add repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  apt: name=docker-ce update_cache=yes

- name: Install docker-compose
  shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Make it executable
  shell: sudo chmod +x /usr/local/bin/docker-compose

- group:
    name: docker
    state: present

- user:
    name: app
    group: docker

- user:
    name: rockyj
    group: docker

- name: restart docker
  systemd: name=docker state=restarted
